---
- name: Make sure autorestic user exists
  ansible.builtin.user:
    name: "{{ autorestic_config_user }}"
  register: autorestic_user_register
  become: true

- name: Set autorestic_user_directory variable
  ansible.builtin.set_fact:
    autorestic_user_directory: "{{ autorestic_user_register.home }}"

- name: Create autorestic_config_path
  ansible.builtin.file:
    path: "{{ autorestic_config_directory }}"
    owner: "{{ autorestic_config_owner }}"
    group: "{{ autorestic_config_group }}"
    state: directory
    mode: "0755"

- name: Copy autorestic config file
  ansible.builtin.copy:
    content: "{{ autorestic_config_yaml | to_json(vault_to_text=True) | from_json | to_nice_yaml }}"
    dest: "{{ autorestic_config_path }}"
    owner: "{{ autorestic_config_owner }}"
    group: "{{ autorestic_config_group }}"
    mode: "{{ autorestic_config_mode }}"
  when: autorestic_config_yaml != "CHANGEME"
  register: config_update
  become: true

- name: Run autorestic check
  ansible.builtin.command: "{{ autorestic_install_path }} check -c {{ autorestic_config_path }}"
  when: autorestic_run_check == true and autorestic_config_yaml != "CHANGEME" and config_update.changed == true
